version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: baseball         #creates 'baseball' DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: insert_baseball_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: